// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';
import {context} from '../models';

export function OnBeforeClose():Promise<boolean>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OnShutdown():Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;
