// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';
import {context} from '../models';
import {manager} from '../models';

export function OnBeforeClose():Promise<boolean>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function OnShutdown():Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OpenFileDialog():Promise<manager.FileResult>;

export function ResizeByCapacityHandler(arg1:string,arg2:number):Promise<string>;

export function RevealInExplorer(arg1:string):Promise<void>;
