// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnBeforeClose() {
  return window['go']['manager']['AppManager']['OnBeforeClose']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['manager']['AppManager']['OnSecondInstanceLaunch'](arg1);
}

export function OnShutdown() {
  return window['go']['manager']['AppManager']['OnShutdown']();
}

export function OnStartup(arg1) {
  return window['go']['manager']['AppManager']['OnStartup'](arg1);
}
