name: Release

on:
  push:
    tags:
      - "v*"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "DecolgenLinuxAmd64"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "DecolgenLinuxArm64"
            platform: "linux/arm64"
            os: "ubuntu-22.04-arm"
          - name: "DecolgenWindowsAmd64"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "DecolgenWindowsArm64"
            platform: "windows/arm64"
            os: "windows-11-arm"
          - name: "DecolgenDarwinUniversal"
            platform: "darwin/universal"
            os: "macos-latest"
          - name: "DecolgenDarwinAmd64"
            platform: "darwin/amd64"
            os: "macos-13"
          - name: "DecolgenDarwinArm64"
            platform: "darwin/arm64"
            os: "macos-latest"
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.23.0"
